### ISSUE TITLE
Improve photometry plot to include reference data with same UCD

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-web#102]
Example case: VISTA J-band data exists but not enough sources in the database have VISTA J data to generate a reference CMD.  We could use the UCDs to generate the reference UCD. For example, use all photometry with em.IR.J photometry to generate the reference data rather than same filter.

**Comment by Will-Cooper** [comment]
To follow ingest enhancing https://github.com/SIMPLE-AstroDB/SIMPLE-db/issues/301

**Comment by kelle** [comment]
When multiple photometry  measurements exists in one UCD, plot the median or mean or something.  DONT try to pick one because that logic doesn't scale.

**Comment by kelle** [comment]
For simplicity, we might just show Gaia G, Gaia Rp, 2MASS JHK_S, and WISE W1 and W2 on the CMDs. _Maybe_ also IRAC, MIPS, and SDSS.

Also minimize the number of colors calculated.

Aim for 10 things in the dropdown.
