### ISSUE TITLE
Revisit use of simple_root

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-web#114]
The construction of simple_root as a link back to itself appears to be a very odd construction and does not work on all environments. We should revisit why we did this and see if we can come up with more stable implementations. 
Came up while testing #113

**Comment by Will-Cooper** [comment]
@dr-rodriguez try replacing simple_root in your windows env with `ln -s simple_app/ simple_root`; that's what it is on reclaim
