### ISSUE TITLE
Test new spectrum loader

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-web#116]
These spectra should now load on the website with the new loader installed:
Example files: 
- https://s3.amazonaws.com/bdnyc/optical_spectra/U10929.fits
- http://simple-bd-archive.org/solo_result/BRI%20B1222-1222
- http://simple-bd-archive.org/solo_result/2MASS%20J01231125-6921379

**Comment by Will-Cooper** [comment]
Hmm, even with the updated astrodbkit2, these don't load with the same error message about "slope"

**Comment by kelle** [comment]
relevant code is around line 107 of `plots.py` where the spectrum is loaded by `astrodbkit2`.

**Comment by kelle** [comment]
@jolielheureux, Please take a look at this and see if you can replicate and try to debug.

**Comment by dr-rodriguez** [comment]
We realized the requirements was pinned to not used the most recent astrodbkit2 and was missing the new loader.
