### ISSUE TITLE
Debug version number

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-web#123]
I am pretty sure the current version of the database. being served is 2022.5 but the footer display says 2022.4. Please investigate. 

Related to SIMPLE-Astrodb/SIMPLE-db#332

**Comment by Will-Cooper** [comment]
This was actually a good check that the cronjob works, and it did! If you check the site now, it says 2022.5. Note that the cronjob serves every week which is Midnight UTC Sundays.
