### ISSUE TITLE
Refactor code for readability

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-web#128]
The current implementation of the code is very unreadable for several reasons:
1. There are no line breaks between sections of code, so for example a function like `multiplotbokeh` (https://github.com/SIMPLE-AstroDB/SIMPLE-web/blob/main/simple_app/plots.py#L218) is nearly 200 lines all back to back with no extra context. These should be split for more easily parsing what is going on, which can help us identify sections of code that could be improved in the future.
2. Comments are being placed at the end of the line rather than at the beginning of logical sections. This is in tandem with the change above. A comment at the end of a line like "x-axis" doesn't really add any value, whereas one describing what's going to happen over the next 5 lines is far more useful.

**Comment by kelle** [comment]
I also noticed some variable names (in `utils.py`) which were not very readable and were missing underscores between words.
