### ISSUE TITLE
Announce website launch

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-web#133]
Write an announcement email about the website being ready for folk to use.

Include link to `raw_query`? 

Include
- [x] Low mass stars slack
- [x] brewster slack
- [x] BDNYC slack
- [x] pyspextool slack
- [x]  jwst direct imaging team slack - Niall
- [x] SIMPLE mailing list
- [x] Low mass star and BD FB group
- [ ] email with a bunch of Bcc'd.

**Comment by Will-Cooper** [comment]
I would actually be happy having `raw_query` as a navigable link. Did the update to `sqlalchemy` help with our previous security concerns @dr-rodriguez? At worst I could build back into the logic that the query only activates on a temporary, copied version of the database.
