### ISSUE TITLE
Return carriage if object is not found

### ISSUE THREAD

**Issue by jrcallingham** [SIMPLE-AstroDB/SIMPLE-web#137]
Hi all,

Nice work on this database/website! We really needed something like this in the UCD community. I just have a feature request - if the source is not known in the database, I recommend the query to return a comment like "Object not found in our database" instead of returning blank. This way the user will be confident about what is being returned. 

Also, I think you are missing BDR J1750+3809 (https://iopscience.iop.org/article/10.3847/2041-8213/abc256/pdf) 

Thanks again for a great website and database! 

Joe

**Comment by kelle** [comment]
Great idea for the website!

I've opened an issue about the missing object in the database repo: [SIMPLE-db/#363](https://github.com/SIMPLE-AstroDB/SIMPLE-db/issues/393)
