### ISSUE TITLE
Looking for GJ 3147

### ISSUE THREAD

**Issue by pfouque58** [SIMPLE-AstroDB/SIMPLE-web#148]
Hi Kelle,

I was testing the SIMPLE database looking for this M7V star (also LHS 1378 or LP 245-10) to get its systemic radial velocity but got this "500 something went wrong" error.

Thanks anyway for this huge work

Pascal Fouqué

**Comment by kelle** [comment]
Thanks for reporting this!  Could you tell us a bit more. How did you get there?  Do you by chance have the URL that generated the 500 error?

**Comment by Will-Cooper** [comment]
Okay I think this is a case of where there are no results for an object it shouldn't make a clickable link to download the results and it should explain that there were no results rather than being blank (#137)

**Comment by kelle** [comment]
Also, is there anything in particularly interesting about this source?  Where did you end up getting the RV from? Basically, I'm trying to understand how high of a priority it should be to ingest.

**Comment by pfouque58** [comment]
Hi Kelle, Will

It was just a test on this late-type M dwarf with contradictory reported RVs in the literature. When clicking on “Results for: GJ 3147” I got the 500 error. But tonight (I’m in Europe), I get a result: a csv file with an incorrect target.

As it is just a test, there is no kind of urgency to solve the problem. I just wanted to report them.

Cheers,

Pascal Fouqué

￼

￼
