### ISSUE TITLE
Link to "missing source" issue template

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-web#154]
On the error page that presents the user with the option to report a missing source, link to the missing source issue template in SIMPLE-db

**Comment by Will-Cooper** [comment]
Ready to be pointed to now https://github.com/SIMPLE-AstroDB/SIMPLE-db/pull/454 is merged, url being https://github.com/SIMPLE-AstroDB/SIMPLE-db/issues/new?assignees=&labels=data+ingestion&projects=&template=missing-source.md&title=Ingest+request%3A+%3Csource+name%3E for missing source and https://github.com/SIMPLE-AstroDB/SIMPLE-db/issues/new?assignees=&labels=data+ingestion&projects=&template=missing-data.md&title=Data+ingest+request+from%3A+%3Cpublication%3E%27 for missing data
