### ISSUE TITLE
Loading animation 

### ISSUE THREAD

**Issue by Ajb2307** [SIMPLE-AstroDB/SIMPLE-web#159]
Here is the loading animated png. I'm not sure if this is the exact format needed. I will update this issue as I find out more. 
![BD-spinning](https://github.com/SIMPLE-AstroDB/SIMPLE-web/assets/67712811/426a3424-6025-4607-a8e4-bcc95ff2575d)

**Comment by kelle** [comment]
Can we make it rotate on it's axis than roll?   Like this? https://media.giphy.com/media/VI2UC13hwWin1MIfmi/giphy.gif

**Comment by Will-Cooper** [comment]
I may be able to do make the rolling just with a png but if you can get a nice spinny or rotatey like Kelle suggests, that would be fab.
