### ISSUE TITLE
JWST NIRSPEC spectrum not plotting

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-web#173]
https://simple-bd-archive.org/load_solo/CWISEP%20J193518.58-154620.3.

The spectrum is there, I don't see an error being thrown, but I don't see any spectrum being displayed.

**Comment by Will-Cooper** [comment]
Okay, the spectrum is being plotted but because it's 2.86--5.14um, it's not immediately apparent. Looks like a bug in my plotting code of assuming SpeX-like spectra.
