### ISSUE TITLE
Make interactive spectrum plot

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-web#24]
Until we have ingested spectra, start with plotting spectral type standards for objects which have spectral types.

**Comment by Will-Cooper** [comment]
Where is the best place to get optical/ nir standards for MLTY?

**Comment by kelle** [comment]
L dwarfs: https://github.com/BDNYC/UltracoolTypingKit/tree/master/spectra/nir

It looks like dwarfachive is down. Is that just me?

**Comment by kelle** [comment]
NIR data here: http://pono.ucsd.edu/~adam/browndwarfs/spexprism/library.html

**Comment by Will-Cooper** [comment]
Linked to https://github.com/SIMPLE-AstroDB/SIMPLE-db/issues/132; need to know where to store spectra + standards

**Comment by Will-Cooper** [comment]
> L dwarfs: https://github.com/BDNYC/UltracoolTypingKit/tree/master/spectra/nir
> 
> It looks like dwarfachive is down. Is that just me?

Also, yes I find the site is down as well.
