### ISSUE TITLE
Make interactive tables

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-web#46]
Make tables which can be sorted by any column and exported.  

Similar to the exomast implementation:
https://catalogs.mast.stsci.edu/eaot

**Comment by Will-Cooper** [comment]
In addition to the search page, where we can return the search results as a file:
Also on the solo_result page, for each category and for all categories (maybe zipped version of each category); a download link to the available data as a csv (maybe also as votable).

**Comment by Will-Cooper** [comment]
> In addition to the search page, where we can return the search results as a file:
> Also on the solo_result page, for each category and for all categories (maybe zipped version of each category); a download link to the available data as a csv (maybe also as votable).

This also goes for being able to bulk download the spectra
