### ISSUE TITLE
Heroku solo result not working

### ISSUE THREAD

**Issue by Will-Cooper** [SIMPLE-AstroDB/SIMPLE-web#51]
The solo result page on the heroku deploy does not load. I had the same bug when running locally until I updated astrodbkit2. The relevant issue is in ```astrodb.inventory``` when it tries to look for the key 'source'. Not sure why heroku isn't using an up to date version of astrobkit2.

**Comment by dr-rodriguez** [comment]
The requirements.txt specifies `astrodbkit2==0.2.1` This should be updated to `astrodbkit2>=0.2.1` or similar to capture the latest version
