### ISSUE TITLE
Get working with postgres database

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-web#80]
Use this issue to report on and discuss process of modifying web app to work with postgres database.

**Comment by huhwhy** [comment]
A snafu happened when I went back to the beginning of my prototyping - 
````
File ~/Research/BDNYC/bdnyc-web-folder/SIMPLE-web/simple_app/simports.py:5 in <module>
    from astrodbkit2.astrodb import Database, REFERENCE_TABLES  # used for pulling out database and querying

ModuleNotFoundError: No module named 'astrodbkit2'``

```

**Comment by kelle** [comment]
Yep, makes sense. Let us know if you need help figuring out how to get `astrodbkit2` installed properly.

**Comment by huhwhy** [comment]
```Astrodbkit2``` seems to be glitching for me. I did the install through pip-install of the web app. Will try and see if I can install directly through pip and also delete my local version of ```Astrodbkit2.```

**Comment by Will-Cooper** [comment]
Tabled for the moment as not currently necessary for the database scale
