### ISSUE TITLE
Update to deploy to reclaim hosting

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-web#88]
To deploy to our Cloud host we will likely need some changes. Heroku took care of a lot of this, but we may need some manual changes and extra files.
I'd recommend checking out https://flask.palletsprojects.com/en/2.1.x/deploying/mod_wsgi/#configuring-apache and seeing if we can implement something along the same lines.

**Comment by kelle** [comment]
Is there a reason why we aren't talking about using a paid Heroku implementation?

**Comment by dr-rodriguez** [comment]
We could look more into Heroku and see what their costs are. But this points to a deeper issue: our application is very specific for that service and not yet fully portable.
