### ISSUE TITLE
Setup HTTPS?

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-web#92]
do we need https?

**Comment by Will-Cooper** [comment]
It's best practice to have so. Not the end of the world as not handling user data but still. [setting up](https://techexpert.tips/apache/enable-https-apache/)

**Comment by Will-Cooper** [comment]
set-up now, free and auto renews every 90 days. Took a bit of time making sure the connection auto-upgraded but it should do now (i.e. if you go to http it'll redirect to https)

**Comment by kelle** [comment]
Our certificate is currently expired. @Will-Cooper , can you look into this?

**Comment by Will-Cooper** [comment]
Should be better now, re-updated certificate. It's weird it's not doing it automatically :(

**Comment by kelle** [comment]
Could you please document somewhere -- maybe in the Wiki? -- what service we're using for our SSL Certificate. If you're not available to renew it, other folks need to have the keys.

**Comment by kelle** [comment]
> You will want to use the Let's Encrypt addon on the load balancer in your environment, not the application server, as the load balancer is what has the Public IP address assigned to it. Once you use the Let's Encrypt add-on on the load balancer, it should automatically renew for you.

**Comment by kelle** [comment]
This looks like it's been done.  Also, setup a monitor on site24x7 to keep us updated in case it goes down again.
