### ISSUE TITLE
Textual changes

### ISSUE THREAD

**Issue by Will-Cooper** [SIMPLE-AstroDB/SIMPLE-web#93]
Note for sources which are missing parts (e.g. spectral types) write "No... in the database"

**Comment by kelle** [comment]
draft text: No spectral type for <source name> in the SIMPLE Archive. If one exists and should be ingested, please open an issue and/or a pull request.

**Comment by kelle** [comment]
maybe we link to an issue template for data ingestion. (https://github.com/SIMPLE-AstroDB/SIMPLE-db/issues/255) 

and (eventually) a link to the contributing data docs.
