### ISSUE TITLE
Release Tracking

### ISSUE THREAD

**Issue by Will-Cooper** [SIMPLE-AstroDB/SIMPLE-web#98]
Github action pin items to keep version of the database. Create micro releases with time stamps. Website needs to track release number and display it on the page and pass to downloadable sheets.

**Comment by kelle** [comment]
The SIMPLE-db now has a Versions table that are tied to releases of SIMPLE-db. see SIMPLE-AstroDB/SIMPLE-db#282

**Comment by Will-Cooper** [comment]
Remember to update astrodbkit2 me

**Comment by kelle** [comment]
I think the website should only show released versions of the database. Probably need to modify the way the database file is uploaded here.

**Comment by kelle** [comment]
website can be edited using data in the Versions table.

**Comment by kelle** [comment]
This process is all complete. Only thing left is for the website to display the current version number.
